services:
  web:
    image: odoo:18.0
    container_name: comix-app
    depends_on:
      - db
    restart: always
    ports:
      - "8069:8069"
    environment:
      - HOST=${ODOO_DB_HOST}
      - USER=${ODOO_DB_USER}
      - PASSWORD=${ODOO_DB_PASSWORD}
    volumes:
      - ./odoo-data:/var/lib/odoo
  db:
    image: postgres:15
    container_name: comix-db
    ports:
      - 5432:5432
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
